version: '3.5'

networks:
  kraicklist:
    driver: bridge

volumes:
  meilisearch:
    driver: local

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - ~/.docker/meilisearch:/var/lib/meilisearch
    ports:
      - "7700:7700"
    networks:
      - kraicklist