version: '3.5'

networks:
  kraicklist_net:
    driver: bridge

volumes:
  meilisearch:
    driver: local

services:
  kraicklist_app:
    container_name: "kraicklist_app"
    build: .
    command: sh -c "./kraicklist"
    ports:
      - "8800:8800"
    environment:
      - APP_MODE=prod
    depends_on:
      - meilisearch
    networks:
      - kraicklist_net

  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - ~/.docker/meilisearch:/var/lib/meilisearch
    ports:
      - "7700:7700"
    networks:
      - kraicklist_net